'use client';

import { createContext, useContext, useSyncExternalStore, type ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Nav
    'nav.home': 'Inicio',
    'nav.store': 'Tienda',
    'nav.drops': 'DROPS',
    'nav.embroidery': 'Bordados',
    'nav.combo': 'C/Estampado',
    'nav.prints': 'Estampado',
    'nav.special': 'Especial',
    'nav.plain': 'Lisas',
    'nav.variety': 'Variedad',
    'nav.caps': 'Gorras',
    'nav.cotizador': 'Cotizador',
    'nav.promos': 'Promociones',
    'nav.account': 'Tripulación',
    'nav.all': 'Ver Todo',
    'nav.language': 'Idioma',
    'nav.currency': 'Moneda',
    
    // Home
    'hero.title': 'Bordados Épicos',
    'hero.subtitle': 'Vístete como un verdadero Nakama',
    'hero.scrolly.badge': 'Nueva Colección',
    'hero.scrolly.title': 'Domina el Grand Line',
    'marquee.welcome': 'DESCUENTO DE BIENVENIDA EN TU 1°, 2° Y 3° COMPRA',
    'marquee.shipping': 'ENVÍO GRATIS A PARTIR DE $1,500',
    'marquee.msi': '3 MSI A PARTIR DE $2,000',
    'marquee.transfer': '5% DE DESCUENTO POR TRANSFERENCIA',
    'hero.promos_btn': 'VER PROMOCIONES',

    // Página de Promociones
    'promos.badge': 'Recompensas de la Tripulación',
    'promos.title': 'Promociones Vigentes',
    'promos.intro': 'Estos son los botines activos en la tienda. Se aplican automáticamente en tu compra: sin códigos raros ni letras invisibles.',
    'promos.welcome.title': 'Descuento de Bienvenida',
    'promos.welcome.tag': '1°, 2° y 3° compra',
    'promos.welcome.desc': 'Tu lealtad se recompensa: cada una de tus primeras compras trae un descuento mayor que la anterior.',
    'promos.welcome.d1': '1° compra: 5% de descuento',
    'promos.welcome.d2': '2° compra: 10% de descuento',
    'promos.welcome.d3': '3° compra: 20% de descuento',
    'promos.welcome.note': 'Necesitas una cuenta Nakama: el descuento se aplica solo al iniciar sesión.',
    'promos.shipping.title': 'Envío Gratis',
    'promos.shipping.tag': 'Desde $1,500',
    'promos.shipping.desc': 'En pedidos a partir de $1,500 MXN la tienda cubre tu envío hasta $140 MXN.',
    'promos.shipping.note': 'Si la paquetería cuesta más del tope, solo pagas la diferencia.',
    'promos.msi.title': '3 Meses Sin Intereses',
    'promos.msi.tag': 'Desde $2,000',
    'promos.msi.desc': 'Difiere tu compra a 3 pagos fijos sin intereses en pedidos desde $2,000 MXN con tarjetas participantes.',
    'promos.msi.note': 'Disponible al elegir pago con tarjeta en el checkout.',
    'promos.transfer.title': 'Descuento por Transferencia',
    'promos.transfer.tag': '5% extra',
    'promos.transfer.desc': 'Paga por transferencia bancaria y llévate 5% de descuento adicional sobre tu total.',
    'promos.transfer.note': 'Se aplica al seleccionar transferencia como método de pago.',
    'promos.terms': 'Consulta términos y condiciones',
    'promos.cta': 'Ir a la Tienda',
    'home.intro.badge': 'Estilo Streetwear Anime',
    'home.intro.title': 'Tu Próximo Tesoro',
    'home.intro.text': 'En Nakama Bordados no solo hacemos ropa, forjamos el equipo para tu próxima aventura. Bordados de alta densidad y diseños exclusivos con la calidad que un futuro Rey de los Piratas merece. Moda anime hecha por fans para fans.',
    'home.intro.btn': 'Explorar Catálogo',
    'home.bestsellers.title': 'LOS MÁS BUSCADOS',
    'home.bestsellers.reward': 'RECOMPENSA: CALIDAD MÁXIMA',
    'home.explore_cats.title': 'EXPLORA POR CATEGORÍA',
    'home.explore_cats.view': 'Ver Colección',
    
    // Store
    'store.loading': 'Cargando Catálogo...',
    'store.hero.badge': 'Catálogo Nakama',
    'store.hero.subtitle': 'Bordados de alta densidad y streetwear premium diseñado para la tripulación.',
    'store.search.results': 'Buscando: {query}',
    'store.tag.results': 'Etiqueta: {tag}',
    'store.load_more': 'CARGAR MÁS PRODUCTOS',
    'store.loading_more': 'EXPLORANDO...',
    'store.end': '🏴‍☠️ Has llegado al final de la colección 🏴‍☠️',
    'store.no_results': 'No encontramos tesoros',
    'store.no_results_text': 'Intenta con otros términos o navega por las categorías.',
    
    // Product
    'product.official': 'Colección Oficial Nakama',
    'product.premium': 'Calidad Premium Grand Line',
    'product.free_shipping_badge': 'Envío Gratis*',
    'product.free_shipping_tip': '*Envío gratis en compras a partir de $1,500 MXN (después de descuentos). La tienda cubre hasta $140 MXN del costo de la guía; si la paquetería cobra más, solo pagas la diferencia.',
    'product.select': 'Seleccionar',
    'product.size_guide': 'Ver Guía de Tallas',
    'product.add_to_cart': '¡Lo Quiero!',
    'product.secure_payment': 'Pago 100% Seguro',
    'product.guaranteed_shipping': 'Envío Garantizado',
    'product.desc_tab': 'Descripción',
    'product.care_tab': 'Cuidado',
    'product.reviews_tab': 'Valoraciones',
    'product.sizes_tab': 'Guía de Tallas',
    'product.sizes_tab_hint': 'Haz clic en las imágenes para ampliar los detalles técnicos.',
    'product.promos_title': 'Promociones Activas',
    'product.promos_link': 'Ver todas las promociones',
    'product.reviews_label': 'valoraciones',
    'product.care_title': '¡Cuida tu equipo como un verdadero pirata!',
    'product.care_1': 'Lavar a mano o ciclo delicado (agua fría).',
    'product.care_2': 'Al revés para proteger el bordado/estampado.',
    'product.care_3': 'Sin blanqueadores químicos.',
    'product.care_4': 'Secar a la sombra (el sol es para navegar, no para secar).',
    'product.care_5': 'No planchar sobre el diseño directamente.',
    'product.related': 'También te puede gustar',
    'product.view': 'Ver Producto',
    'product.added': '¡{name} agregado al carrito!',
    'product.warning.luffy.title': '¡OI, NAKAMA!',
    'product.warning.luffy.phrase': '¡Elige tu estilo antes de zarpar al Grand Line!',
    'product.warning.zoro.title': '¡ZORO SE PERDIÓ!',
    'product.warning.zoro.phrase': 'Y tú también si no eliges una talla primero...',
    'product.warning.sanji.title': '¡SANJI ESTÁ FURIOSO!',
    'product.warning.sanji.phrase': '¡No puedes ordenar sin elegir los ingredientes (variaciones)!',
    'product.warning.chopper.title': '¡CHOPPER ESTÁ ASUSTADO!',
    'product.warning.chopper.phrase': '¡Doctor! ¡Doctor! ¡Falta seleccionar el color!',
    'product.warning.close': '¡Entendido!',

    // Checkout & Cart
    'cart.page_title': 'Valida tu Botín',
    'cart.item_table.product': 'Producto',
    'cart.item_table.price': 'Precio',
    'cart.item_table.qty': 'Cant.',
    'cart.item_table.total': 'Subtotal',
    'cart.finalize_btn': 'Finalizar Compra en el Barco Principal',
    'cart.continue_btn': 'Seguir Buscando Tesoros',
    'checkout.title': 'Finalizar Pedido',
    'checkout.billing': 'Datos de Envío',
    'checkout.email': 'Correo Electrónico',
    'checkout.first_name': 'Nombre',
    'checkout.last_name': 'Apellidos',
    'checkout.phone': 'Teléfono',
    'checkout.address': 'Dirección (Calle y Número)',
    'checkout.apartment': 'Depto / Suite / Referencias',
    'checkout.city': 'Ciudad',
    'checkout.state': 'Estado',
    'checkout.postcode': 'Código Postal',
    'checkout.country': 'País',
    'checkout.summary': 'Resumen del Tesoro',
    'checkout.shipping_method': 'Método de Envío',
    'checkout.payment_method': 'Método de Pago',
    'checkout.place_order': 'Zarpar Pedido',
    'checkout.processing': 'Procesando...',
    'checkout.coupon.placeholder': 'Ej. NAKAMA15',
    'checkout.coupon.apply': 'Aplicar código',
    'checkout.coupon.toggle': '¿Tienes otro código?',
    'checkout.coupon.help': 'Escribe un código manual de Nakama o el cupón que recibiste para recuperar tu carrito.',
    'checkout.coupon.label': 'Código promocional',
    'checkout.coupon.empty': 'Escribe un código promocional.',
    'checkout.coupon.invalid': 'El código no es válido.',
    'checkout.coupon.validating': 'Validando…',
    'checkout.coupon.remove': 'Quitar código promocional',
    'checkout.coupon.manual_success': 'Código reconocido. En el checkout podrás comparar las promociones disponibles.',
    'checkout.coupon.native_success': 'Cupón aplicado. WooCommerce confirmará el descuento antes del pago.',
    'checkout.affiliate.title': 'Código de afiliado',
    'checkout.affiliate.help': 'Apoya a tu creador favorito. Este código sustituye cualquier otra promoción.',
    'checkout.affiliate.label': 'Escribe el código del afiliado',
    'checkout.affiliate.placeholder': 'Ej. NICO',
    'checkout.affiliate.apply': 'Aplicar código',
    'checkout.affiliate.validating': 'Validando…',
    'checkout.affiliate.empty': 'Escribe un código de afiliado.',
    'checkout.affiliate.invalid': 'El código de afiliado no es válido.',
    'checkout.affiliate.remove': 'Quitar código de afiliado',
    'checkout.affiliate.referral': 'Referencia guardada',
    'affiliates.title': 'Panel de Afiliados',
    'affiliates.login': 'Inicia sesión para ver tu panel de afiliado.',
    'affiliates.loginCta': 'Ir a Mi Cuenta',
    'affiliates.denied': 'Tu cuenta no tiene acceso al programa de afiliados.',
    'affiliates.fiscal.title': 'Constancia de Situación Fiscal',
    'affiliates.fiscal.missing': 'Sube tu constancia para habilitar la información financiera.',
    'affiliates.fiscal.pending': 'Tu constancia está en revisión.',
    'affiliates.fiscal.rejected': 'Tu constancia fue rechazada. Revisa el motivo y envía una nueva versión.',
    'affiliates.fiscal.approved': 'Constancia aprobada.',
    'affiliates.fiscal.label': 'Selecciona tu constancia en PDF',
    'affiliates.fiscal.upload': 'Enviar constancia',
    'affiliates.fiscal.uploading': 'Enviando…',
    'affiliates.summary.label': 'Resumen financiero del mes',
    'affiliates.summary.sales': 'Ventas válidas',
    'affiliates.summary.commission': 'Comisión acumulada',
    'affiliates.summary.salesCount': 'ventas',
    'affiliates.summary.adjustmentsCount': 'ajustes',
    'affiliates.summary.commissionRule': '10% sobre subtotal elegible antes del descuento',
    'affiliates.code': 'Tu código',
    'affiliates.link': 'Tu enlace',
    'affiliates.sales.title': 'Movimientos del periodo',
    'affiliates.sales.empty': 'Aún no hay ventas registradas.',
    'affiliates.sales.sale': 'Venta',
    'affiliates.sales.adjustment': 'Ajuste',
    'affiliates.sales.base': 'Base MXN',
    'affiliates.sales.commission': 'Comisión',
    'affiliates.history.kicker': 'Historial mensual',
    'affiliates.history.title': 'Cierres y pagos',
    'affiliates.history.period': 'Periodo',
    'affiliates.history.empty': 'Aún no hay cierres mensuales.',
    'affiliates.history.sales': 'Ventas del periodo',
    'affiliates.history.refunds': 'Devoluciones',
    'affiliates.history.ledgerAdjustments': 'Ajustes de ventas',
    'affiliates.history.gross': 'Comisión bruta',
    'affiliates.history.isr': 'ISR retenido (capturado por administración)',
    'affiliates.history.iva': 'IVA retenido (capturado por administración)',
    'affiliates.history.adjustments': 'Otros ajustes (capturados por administración)',
    'affiliates.history.net': 'Neto del periodo',
    'affiliates.history.paid': 'Pagado',
    'affiliates.history.approved': 'Pago pendiente',
    'affiliates.history.closed': 'Cierre en revisión',
    'affiliates.history.draft': 'Cierre en proceso',
    'affiliates.history.receipt': 'Descargar comprobante',
    'affiliates.history.receiptDownloading': 'Preparando comprobante…',
    'affiliates.history.receiptError': 'No pudimos descargar tu comprobante.',
    'affiliates.history.reversed': 'Pago revertido',
    'affiliates.history.carry': 'Las devoluciones posteriores a un cierre se descuentan en el siguiente mes abierto; el cierre anterior no se modifica.',
    'affiliates.history.manual': 'Estos importes fueron capturados por administración siguiendo las indicaciones del contador; no son un cálculo fiscal automático.',
    'affiliates.retry': 'Reintentar',
    'affiliates.error': 'No pudimos cargar tu panel.',
    'affiliates.loading': 'Cargando panel de afiliados…',
    'affiliates.sessionExpired': 'Tu sesión terminó. Inicia sesión de nuevo para continuar.',
    'affiliates.mission.label': 'Centro de misión mensual',
    'affiliates.mission.kicker': 'Programa mensual',
    'affiliates.mission.title': 'Manga impacto',
    'affiliates.mission.intro': 'Convierte tu alcance en recompensas y mantén visible cada paso de tu colaboración con Nakama.',
    'affiliates.mission.loading': 'Cargando tu misión mensual…',
    'affiliates.mission.loadError': 'No pudimos cargar la misión mensual. Tus datos financieros siguen disponibles.',
    'affiliates.mission.progressKicker': 'Meta del próximo mes',
    'affiliates.mission.progressTitle': 'Tu impacto mensual',
    'affiliates.mission.currentReward': 'Recompensa actual',
    'affiliates.mission.oneProduct': '1 prenda',
    'affiliates.mission.manyProducts': '{count} prendas',
    'affiliates.mission.remaining': 'Te faltan {amount} para desbloquear {count} prendas.',
    'affiliates.mission.maxReached': '¡Meta máxima alcanzada para el siguiente mes!',
    'affiliates.mission.noCarry': 'El cupo se recalcula cada mes y no se acumula.',
    'affiliates.mission.milestones': 'Metas de prendas del mes',
    'affiliates.mission.productKicker': 'Recompensa mensual',
    'affiliates.mission.productTitle': 'Elige tu prenda',
    'affiliates.mission.unit': 'unidad disponible',
    'affiliates.mission.units': 'unidades disponibles',
    'affiliates.mission.vipCatalog': 'Tu acceso VIP incluye Drops y Edición especial cuando estén disponibles; no garantiza aprobación.',
    'affiliates.mission.standardCatalog': 'Drops y Edición especial están excluidos de esta selección.',
    'affiliates.mission.noPriceLimit': 'Sin límite de precio dentro del catálogo elegible.',
    'affiliates.mission.selected': 'seleccionadas',
    'affiliates.mission.variation': 'Talla o variante',
    'affiliates.mission.productsEmpty': 'No hay productos elegibles disponibles en este momento.',
    'affiliates.mission.addressTitle': 'Dirección confirmada',
    'affiliates.mission.shippingCovered': 'Nakama cubre el costo del envío.',
    'affiliates.mission.addressConfirm': 'Confirmo que esta dirección es correcta.',
    'affiliates.mission.addressIncomplete': 'Completa tu dirección y teléfono en Mi Cuenta antes de solicitar la prenda.',
    'affiliates.mission.sendRequest': 'Enviar solicitud',
    'affiliates.mission.requestSent': 'Solicitud enviada. Nakama la revisará antes de prepararla.',
    'affiliates.mission.requestError': 'No pudimos enviar la solicitud. Revisa tu selección e inténtalo de nuevo.',
    'affiliates.mission.sending': 'Enviando…',
    'affiliates.mission.requestStatus.draft': 'Borrador',
    'affiliates.mission.requestStatus.submitted': 'Solicitud en revisión',
    'affiliates.mission.requestStatus.approved': 'Solicitud aprobada',
    'affiliates.mission.requestStatus.preparing': 'Preparando tu envío',
    'affiliates.mission.requestStatus.shipped': 'Prenda enviada',
    'affiliates.mission.requestStatus.completed': 'Entrega completada',
    'affiliates.mission.requestStatus.rejected': 'Solicitud rechazada',
    'affiliates.mission.requestStatus.cancelled': 'Solicitud cancelada',
    'affiliates.mission.evidenceKicker': 'Tu parte de la misión',
    'affiliates.mission.evidenceTitle': 'Comparte tu impacto',
    'affiliates.mission.tagReminder': 'Etiqueta en cada publicación a',
    'affiliates.mission.officialAccounts': 'las cuentas oficiales de Nakama Bordados',
    'affiliates.mission.codeReminder': 'Invita a tu audiencia a comprar en la tienda con tu código.',
    'affiliates.mission.evidenceWaiting': 'Podrás enviar las evidencias cuando tu prenda haya sido enviada.',
    'affiliates.mission.reel1': 'Reel 1',
    'affiliates.mission.reel2': 'Reel 2',
    'affiliates.mission.story': 'Historia',
    'affiliates.mission.bonusLabel': 'Reel o publicación bonus',
    'affiliates.mission.required': 'obligatorio',
    'affiliates.mission.optional': 'opcional',
    'affiliates.mission.evidenceRequired': 'Este enlace es obligatorio.',
    'affiliates.mission.evidenceHttps': 'Usa una URL segura que empiece con https://.',
    'affiliates.mission.evidenceSent': 'Evidencias enviadas para revisión manual.',
    'affiliates.mission.evidenceError': 'No pudimos enviar las evidencias. Revisa los enlaces e inténtalo de nuevo.',
    'affiliates.mission.evidenceStatus.pending': 'Pendiente',
    'affiliates.mission.evidenceStatus.approved': 'Aprobada',
    'affiliates.mission.evidenceStatus.rejected': 'Rechazada',
    'affiliates.mission.bonus': 'El Reel o publicación bonus puede darte prioridad para elegir un Drop como prenda del mes, pero no es una garantía, no concede VIP y no aumenta tu cupo.',
    'affiliates.mission.sendEvidence': 'Enviar evidencias',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Envío',
    'checkout.discount': 'Descuento',
    'checkout.total': 'Total',
    'checkout.empty': 'Tu barco está vacío',
    'checkout.back': 'Volver a la tienda',
    'checkout.free': '¡GRATIS!',

    // Account
    'account.title': 'Centro de Mando',
    'account.welcome': '¡Bienvenido a bordo, {name}!',
    'account.logout': 'Abandonar Barco',
    'account.orders': 'Mis Pedidos',
    'account.no_orders': 'Aún no tienes botines registrados.',
    'account.profile': 'Perfil Nakama',
    'account.email': 'Email',
    'account.member_since': 'Miembro desde',
    'account.login.title': 'Acceso a la Tripulación',
    'account.login.user': 'Usuario o Email',
    'account.login.pass': 'Contraseña',
    'account.login.btn': 'Entrar al Barco',
    'account.login.reset': 'Restablecer contraseña',
    'account.login.error': 'Credenciales piratas inválidas',
    'account.login.no_account': '¿No tienes cuenta? Únete a la tripulación',
    'account.register.title': 'Únete a la Tripulación',
    'account.register.first': 'Nombre',
    'account.register.last': 'Apellido',
    'account.register.email': 'Email',
    'account.register.phone': 'Teléfono (WhatsApp)',
    'account.register.pass': 'Contraseña (mínimo 6 caracteres)',
    'account.register.btn': 'Crear mi cuenta',
    'account.register.error': 'No se pudo crear la cuenta',
    'account.register.have_account': '¿Ya tienes cuenta? Inicia sesión',

    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Todo lo que necesitas saber para tu próxima misión.',
    'faq.still_doubts': '¿Aún tienes dudas?',
    'faq.contact': 'Contáctanos por WhatsApp',
    'faq.q1': '¿Cuánto tiempo tarda en llegar mi pedido?',
    'faq.a1': 'El tiempo de elaboración es de 7 a 15 días hábiles, ya que cada pieza se fabrica bajo pedido para asegurar la máxima calidad. Una vez enviado, el tiempo de entrega depende de la paquetería (Estafeta o FedEx), usualmente de 2 a 5 días.',
    'faq.q2': '¿Hacen envíos a todo México?',
    'faq.a2': 'Sí, realizamos envíos a toda la República Mexicana a través de Envia.com con las mejores paqueterías del país.',
    'faq.q3': '¿Cómo puedo rastrear mi paquete?',
    'faq.a3': 'Puedes rastrearlo directamente en nuestra sección \'Mi Cuenta\' si estás registrado, o ingresando el número de guía que te enviaremos por correo en el portal oficial de la paquetería correspondiente.',
    'faq.q4': '¿Tienen tienda física?',
    'faq.a4': 'Actualmente operamos exclusivamente de manera online para poder ofrecer la mayor variedad de diseños a nakamas de todo México.',
    'faq.q5': '¿Qué cuidados debo tener con mi prenda bordada?',
    'faq.a5': 'Recomendamos lavar la prenda al revés con agua fría, no usar secadora y nunca planchar directamente sobre el bordado para preservar la densidad y el color de los hilos.',

    // Size Guide
    'sizes.title': 'Guía de Tallas',
    'sizes.subtitle': 'Asegúrate de que tu equipo te quede perfecto antes de zarpar.',
    'sizes.badge': 'Guía',
    'sizes.pro_tip': '💡 Pro-Tip Nakama',
    'sizes.pro_tip_text': 'Nuestras tallas son estándar mexicanas. Si buscas un estilo más relajado o \'baggy\', te recomendamos pedir una talla más arriba de lo habitual, especialmente en nuestras piezas bordadas.',
    'sizes.cat.tshirts': 'Playeras',
    'sizes.cat.oversize': 'Oversize',
    'sizes.cat.sweatshirts': 'Sudaderas',
    'sizes.cat.hoodies': 'Hoodies',
    'sizes.cat.acid': 'Acid Wash',
    'sizes.cat.shorts': 'Shorts',
    'sizes.cat.chroma': 'Cromas',

    // Legal
    'privacy.title': 'Aviso de Privacidad',
    'privacy.subtitle': 'Protegiendo tus datos como el One Piece.',
    'terms.title': 'Términos y Condiciones',
    'terms.subtitle': 'Las reglas de este barco para una navegación segura.',

    // Cookies
    'cookies.title': 'Aviso de cookies',
    'cookies.text': 'Usamos cookies propias y de terceros (Google Analytics y Meta) para analizar la navegación y mejorar tu experiencia. Las funciones esenciales de la tienda no dependen de ellas.',
    'cookies.link': 'Consulta nuestro Aviso de Privacidad',
    'cookies.accept': 'Aceptar',
    'cookies.reject': 'Rechazar',

    // Bot
    'bot.welcome': '¡Oi, Nakama! 🍖 Soy Luffy, el guardián de este barco. ¡No pierdas tiempo escribiendo, mejor pícale a los botones para encontrar tu tesoro! 🏴‍☠️',
    'bot.status': '● NAVEGANDO POR EL MENÚ',
    'bot.hint': '¿A dónde zarpamos, Nakama?',
    'bot.btn.all': '🔥 Ver Todo el Catálogo',
    'bot.btn.embroidery': '🪡 Ver Bordados',
    'bot.btn.prints': '👕 Ver Estampados',
    'bot.btn.special': '✨ Edición Especial',
    'bot.btn.sizes': '📐 Guía de Tallas',
    'bot.btn.tracking': '🔍 Rastreo de Pedido',
    'bot.btn.faq': '❓ Preguntas Frecuentes',
    'bot.btn.privacy': '📄 Aviso de Privacidad',
    'bot.btn.crew': '🏴‍☠️ Hablar con Tripulación',
    
    // Global & UI
    'cart.title': 'Tu Botín',
    'cart.empty': 'Tu carrito está vacío',
    'checkout.button': 'Ir a la Caja',
    'theme.dark': 'Modo Oscuro',
    'theme.light': 'Modo Claro',
    
    // Footer
    'footer.description': 'Forjando el equipo de los próximos Reyes de los Piratas. Streetwear anime de alta densidad.',
    'footer.support': 'Soporte',
    'footer.legal': 'Legal',
    'footer.secure_payment': 'Pago Seguro',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.faq': 'Preguntas Frecuentes',
    'footer.size_guide': 'Guía de Tallas',
    'footer.terms': 'Términos y Condiciones',
    'footer.privacy': 'Aviso de Privacidad',
    'footer.dev': 'Diseño y Desarrollo',
  },
  en: {
    // Nav
    'nav.home': 'Home',
    'nav.store': 'Store',
    'nav.drops': 'DROPS',
    'nav.embroidery': 'Embroidery',
    'nav.combo': 'W/Prints',
    'nav.prints': 'Prints',
    'nav.special': 'Special',
    'nav.plain': 'Plain',
    'nav.variety': 'Variety',
    'nav.caps': 'Caps',
    'nav.cotizador': 'Custom Quote',
    'nav.promos': 'Promotions',
    'nav.account': 'Crew',
    'nav.all': 'View All',
    'nav.language': 'Language',
    'nav.currency': 'Currency',
    
    // Home
    'hero.title': 'Epic Embroidery',
    'hero.subtitle': 'Dress like a true Nakama',
    'hero.scrolly.badge': 'New Collection',
    'hero.scrolly.title': 'Master the Grand Line',
    'marquee.welcome': 'WELCOME DISCOUNT ON YOUR 1ST, 2ND & 3RD PURCHASE',
    'marquee.shipping': 'FREE SHIPPING FROM $1,500 MXN',
    'marquee.msi': '3 MONTHS INTEREST-FREE FROM $2,000 MXN',
    'marquee.transfer': '5% OFF WITH BANK TRANSFER',
    'hero.promos_btn': 'SEE PROMOTIONS',

    // Promotions page
    'promos.badge': 'Crew Rewards',
    'promos.title': 'Current Promotions',
    'promos.intro': 'These are the active rewards in the store. They apply automatically at checkout: no weird codes, no fine print tricks.',
    'promos.welcome.title': 'Welcome Discount',
    'promos.welcome.tag': '1st, 2nd & 3rd purchase',
    'promos.welcome.desc': 'Loyalty pays off: each of your first purchases brings a bigger discount than the last.',
    'promos.welcome.d1': '1st purchase: 5% off',
    'promos.welcome.d2': '2nd purchase: 10% off',
    'promos.welcome.d3': '3rd purchase: 20% off',
    'promos.welcome.note': 'A Nakama account is required: the discount only applies while logged in.',
    'promos.shipping.title': 'Free Shipping',
    'promos.shipping.tag': 'From $1,500 MXN',
    'promos.shipping.desc': 'On orders from $1,500 MXN the store covers your shipping up to $140 MXN.',
    'promos.shipping.note': 'If the carrier costs more than the cap, you only pay the difference.',
    'promos.msi.title': '3 Months Interest-Free',
    'promos.msi.tag': 'From $2,000 MXN',
    'promos.msi.desc': 'Split your purchase into 3 fixed interest-free payments on orders from $2,000 MXN with participating cards.',
    'promos.msi.note': 'Available when paying by card at checkout.',
    'promos.transfer.title': 'Bank Transfer Discount',
    'promos.transfer.tag': '5% extra',
    'promos.transfer.desc': 'Pay by bank transfer and get an extra 5% off your total.',
    'promos.transfer.note': 'Applied when selecting bank transfer as payment method.',
    'promos.terms': 'See terms and conditions',
    'promos.cta': 'Go to the Store',
    'home.intro.badge': 'Anime Streetwear Style',
    'home.intro.title': 'Your Next Treasure',
    'home.intro.text': 'At Nakama Bordados we don\'t just make clothes, we forge the gear for your next adventure. High-density embroidery and exclusive designs with the quality a future Pirate King deserves. Anime fashion made by fans for fans.',
    'home.intro.btn': 'Explore Catalog',
    'home.bestsellers.title': 'MOST WANTED',
    'home.bestsellers.reward': 'REWARD: MAXIMUM QUALITY',
    'home.explore_cats.title': 'EXPLORE BY CATEGORY',
    'home.explore_cats.view': 'View Collection',
    
    // Store
    'store.loading': 'Loading Catalog...',
    'store.hero.badge': 'Nakama Catalog',
    'store.hero.subtitle': 'High-density embroidery and premium streetwear designed for the crew.',
    'store.search.results': 'Searching: {query}',
    'store.tag.results': 'Tag: {tag}',
    'store.load_more': 'LOAD MORE PRODUCTS',
    'store.loading_more': 'EXPLORING...',
    'store.end': '🏴‍☠️ You have reached the end of the collection 🏴‍☠️',
    'store.no_results': 'No treasures found',
    'store.no_results_text': 'Try other terms or navigate through the categories.',
    
    // Product
    'product.official': 'Official Nakama Collection',
    'product.premium': 'Grand Line Premium Quality',
    'product.free_shipping_badge': 'Free Shipping*',
    'product.free_shipping_tip': '*Free shipping on orders from $1,500 MXN (after discounts). The store covers up to $140 MXN of the shipping label; if the carrier charges more, you only pay the difference.',
    'product.select': 'Select',
    'product.size_guide': 'View Size Guide',
    'product.add_to_cart': 'I Want It!',
    'product.secure_payment': '100% Secure Payment',
    'product.guaranteed_shipping': 'Guaranteed Shipping',
    'product.desc_tab': 'Description',
    'product.care_tab': 'Care',
    'product.reviews_tab': 'Reviews',
    'product.sizes_tab': 'Size Guide',
    'product.sizes_tab_hint': 'Click the images to zoom into the technical details.',
    'product.promos_title': 'Active Promotions',
    'product.promos_link': 'See all promotions',
    'product.reviews_label': 'reviews',
    'product.care_title': 'Take care of your gear like a true pirate!',
    'product.care_1': 'Hand wash or delicate cycle (cold water).',
    'product.care_2': 'Inside out to protect embroidery/print.',
    'product.care_3': 'No chemical bleaches.',
    'product.care_4': 'Dry in shade (sun is for sailing, not drying).',
    'product.care_5': 'Do not iron directly on the design.',
    'product.related': 'You may also like',
    'product.view': 'View Product',
    'product.added': '{name} added to cart!',
    'product.warning.luffy.title': 'OI, NAKAMA!',
    'product.warning.luffy.phrase': 'Choose your style before sailing to the Grand Line!',
    'product.warning.zoro.title': 'ZORO GOT LOST!',
    'product.warning.zoro.phrase': 'And so will you if you don\'t choose a size first...',
    'product.warning.sanji.title': 'SANJI IS FURIOUS!',
    'product.warning.sanji.phrase': 'You can\'t order without choosing the ingredients (variations)!',
    'product.warning.chopper.title': 'CHOPPER IS SCARED!',
    'product.warning.chopper.phrase': 'Doctor! Doctor! Color selection is missing!',
    'product.warning.close': 'Understood!',

    // Checkout & Cart
    'checkout.title': 'Checkout',
    'checkout.billing': 'Shipping Details',
    'checkout.email': 'Email',
    'checkout.first_name': 'First Name',
    'checkout.last_name': 'Last Name',
    'checkout.phone': 'Phone',
    'checkout.address': 'Address (Street and Number)',
    'checkout.apartment': 'Apartment / Suite / References',
    'checkout.city': 'City',
    'checkout.state': 'State',
    'checkout.postcode': 'Postcode',
    'checkout.country': 'Country',
    'checkout.summary': 'Treasure Summary',
    'checkout.shipping_method': 'Shipping Method',
    'checkout.payment_method': 'Payment Method',
    'checkout.place_order': 'Sail Order',
    'checkout.processing': 'Processing...',
    'checkout.coupon.placeholder': 'E.g. NAKAMA15',
    'checkout.coupon.apply': 'Apply code',
    'checkout.coupon.toggle': 'Do you have another code?',
    'checkout.coupon.help': 'Enter a manual Nakama code or the coupon you received to recover your cart.',
    'checkout.coupon.label': 'Promotional code',
    'checkout.coupon.empty': 'Enter a promotional code.',
    'checkout.coupon.invalid': 'The code is not valid.',
    'checkout.coupon.validating': 'Validating…',
    'checkout.coupon.remove': 'Remove promotional code',
    'checkout.coupon.manual_success': 'Code recognized. At checkout you can compare the available promotions.',
    'checkout.coupon.native_success': 'Coupon applied. WooCommerce will confirm the discount before payment.',
    'checkout.affiliate.title': 'Affiliate code',
    'checkout.affiliate.help': 'Support your favorite creator. This code replaces any other promotion.',
    'checkout.affiliate.label': 'Enter the affiliate code',
    'checkout.affiliate.placeholder': 'E.g. NICO',
    'checkout.affiliate.apply': 'Apply code',
    'checkout.affiliate.validating': 'Validating…',
    'checkout.affiliate.empty': 'Enter an affiliate code.',
    'checkout.affiliate.invalid': 'The affiliate code is not valid.',
    'checkout.affiliate.remove': 'Remove affiliate code',
    'checkout.affiliate.referral': 'Saved referral',
    'affiliates.title': 'Affiliate Dashboard',
    'affiliates.login': 'Sign in to view your affiliate dashboard.',
    'affiliates.loginCta': 'Go to My Account',
    'affiliates.denied': 'Your account does not have access to the affiliate program.',
    'affiliates.fiscal.title': 'Tax Status Certificate',
    'affiliates.fiscal.missing': 'Upload your certificate to unlock financial information.',
    'affiliates.fiscal.pending': 'Your certificate is under review.',
    'affiliates.fiscal.rejected': 'Your certificate was rejected. Review the reason and submit a new version.',
    'affiliates.fiscal.approved': 'Certificate approved.',
    'affiliates.fiscal.label': 'Select your certificate as a PDF',
    'affiliates.fiscal.upload': 'Submit certificate',
    'affiliates.fiscal.uploading': 'Uploading…',
    'affiliates.summary.label': 'Monthly financial summary',
    'affiliates.summary.sales': 'Eligible sales',
    'affiliates.summary.commission': 'Accrued commission',
    'affiliates.summary.salesCount': 'sales',
    'affiliates.summary.adjustmentsCount': 'adjustments',
    'affiliates.summary.commissionRule': '10% of the eligible subtotal before discount',
    'affiliates.code': 'Your code',
    'affiliates.link': 'Your link',
    'affiliates.sales.title': 'Period activity',
    'affiliates.sales.empty': 'No sales have been recorded yet.',
    'affiliates.sales.sale': 'Sale',
    'affiliates.sales.adjustment': 'Adjustment',
    'affiliates.sales.base': 'MXN base',
    'affiliates.sales.commission': 'Commission',
    'affiliates.history.kicker': 'Monthly history',
    'affiliates.history.title': 'Closures and payments',
    'affiliates.history.period': 'Period',
    'affiliates.history.empty': 'There are no monthly closures yet.',
    'affiliates.history.sales': 'Period sales',
    'affiliates.history.refunds': 'Refunds',
    'affiliates.history.ledgerAdjustments': 'Sales adjustments',
    'affiliates.history.gross': 'Gross commission',
    'affiliates.history.isr': 'ISR withheld (entered by administration)',
    'affiliates.history.iva': 'IVA withheld (entered by administration)',
    'affiliates.history.adjustments': 'Other adjustments (entered by administration)',
    'affiliates.history.net': 'Period net',
    'affiliates.history.paid': 'Paid',
    'affiliates.history.approved': 'Payment pending',
    'affiliates.history.closed': 'Closure under review',
    'affiliates.history.draft': 'Closure in progress',
    'affiliates.history.receipt': 'Download receipt',
    'affiliates.history.receiptDownloading': 'Preparing receipt…',
    'affiliates.history.receiptError': 'We could not download your receipt.',
    'affiliates.history.reversed': 'Payment reversed',
    'affiliates.history.carry': 'Refunds received after a closure are deducted from the next open month; the previous closure is not changed.',
    'affiliates.history.manual': 'These amounts were entered by administration following the accountant’s instructions; they are not an automatic tax calculation.',
    'affiliates.retry': 'Try again',
    'affiliates.error': 'We could not load your dashboard.',
    'affiliates.loading': 'Loading affiliate dashboard…',
    'affiliates.sessionExpired': 'Your session ended. Sign in again to continue.',
    'affiliates.mission.label': 'Monthly mission center',
    'affiliates.mission.kicker': 'Monthly program',
    'affiliates.mission.title': 'Impact manga',
    'affiliates.mission.intro': 'Turn your reach into rewards and keep every step of your Nakama collaboration visible.',
    'affiliates.mission.loading': 'Loading your monthly mission…',
    'affiliates.mission.loadError': 'We could not load the monthly mission. Your financial information is still available.',
    'affiliates.mission.progressKicker': 'Next month goal',
    'affiliates.mission.progressTitle': 'Your monthly impact',
    'affiliates.mission.currentReward': 'Current reward',
    'affiliates.mission.oneProduct': '1 garment',
    'affiliates.mission.manyProducts': '{count} garments',
    'affiliates.mission.remaining': 'You need {amount} more to unlock {count} garments.',
    'affiliates.mission.maxReached': 'Maximum goal reached for next month!',
    'affiliates.mission.noCarry': 'The allowance is recalculated every month and does not carry over.',
    'affiliates.mission.milestones': 'Monthly garment goals',
    'affiliates.mission.productKicker': 'Monthly reward',
    'affiliates.mission.productTitle': 'Choose your garment',
    'affiliates.mission.unit': 'unit available',
    'affiliates.mission.units': 'units available',
    'affiliates.mission.vipCatalog': 'Your VIP access includes Drops and Special Editions when available; approval is not guaranteed.',
    'affiliates.mission.standardCatalog': 'Drops and Special Editions are excluded from this selection.',
    'affiliates.mission.noPriceLimit': 'No price limit within the eligible catalog.',
    'affiliates.mission.selected': 'selected',
    'affiliates.mission.variation': 'Size or variation',
    'affiliates.mission.productsEmpty': 'There are no eligible products available right now.',
    'affiliates.mission.addressTitle': 'Confirmed address',
    'affiliates.mission.shippingCovered': 'Nakama covers the shipping cost.',
    'affiliates.mission.addressConfirm': 'I confirm that this address is correct.',
    'affiliates.mission.addressIncomplete': 'Complete your address and phone number in My Account before requesting a garment.',
    'affiliates.mission.sendRequest': 'Send request',
    'affiliates.mission.requestSent': 'Request sent. Nakama will review it before preparation.',
    'affiliates.mission.requestError': 'We could not send the request. Review your selection and try again.',
    'affiliates.mission.sending': 'Sending…',
    'affiliates.mission.requestStatus.draft': 'Draft',
    'affiliates.mission.requestStatus.submitted': 'Request under review',
    'affiliates.mission.requestStatus.approved': 'Request approved',
    'affiliates.mission.requestStatus.preparing': 'Preparing your shipment',
    'affiliates.mission.requestStatus.shipped': 'Garment shipped',
    'affiliates.mission.requestStatus.completed': 'Delivery completed',
    'affiliates.mission.requestStatus.rejected': 'Request rejected',
    'affiliates.mission.requestStatus.cancelled': 'Request cancelled',
    'affiliates.mission.evidenceKicker': 'Your part of the mission',
    'affiliates.mission.evidenceTitle': 'Share your impact',
    'affiliates.mission.tagReminder': 'Tag each post with',
    'affiliates.mission.officialAccounts': 'the official Nakama Bordados accounts',
    'affiliates.mission.codeReminder': 'Invite your audience to shop with your code.',
    'affiliates.mission.evidenceWaiting': 'You can submit evidence after your garment has shipped.',
    'affiliates.mission.reel1': 'Reel 1',
    'affiliates.mission.reel2': 'Reel 2',
    'affiliates.mission.story': 'Story',
    'affiliates.mission.bonusLabel': 'Bonus Reel or post',
    'affiliates.mission.required': 'required',
    'affiliates.mission.optional': 'optional',
    'affiliates.mission.evidenceRequired': 'This link is required.',
    'affiliates.mission.evidenceHttps': 'Use a secure URL beginning with https://.',
    'affiliates.mission.evidenceSent': 'Evidence submitted for manual review.',
    'affiliates.mission.evidenceError': 'We could not submit the evidence. Review the links and try again.',
    'affiliates.mission.evidenceStatus.pending': 'Pending',
    'affiliates.mission.evidenceStatus.approved': 'Approved',
    'affiliates.mission.evidenceStatus.rejected': 'Rejected',
    'affiliates.mission.bonus': 'The bonus Reel or post may give you priority when choosing a Drop as your monthly garment, but it is not guaranteed, does not grant VIP, and does not increase your allowance.',
    'affiliates.mission.sendEvidence': 'Submit evidence',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Shipping',
    'checkout.discount': 'Discount',
    'checkout.total': 'Total',
    'checkout.empty': 'Your ship is empty',
    'checkout.back': 'Back to Store',
    'checkout.free': 'FREE!',

    // Account
    'account.title': 'Command Center',
    'account.welcome': 'Welcome aboard, {name}!',
    'account.logout': 'Leave Ship',
    'account.orders': 'My Orders',
    'account.no_orders': 'No loot recorded yet.',
    'account.profile': 'Nakama Profile',
    'account.email': 'Email',
    'account.member_since': 'Member since',
    'account.login.title': 'Crew Access',
    'account.login.user': 'Username or Email',
    'account.login.pass': 'Password',
    'account.login.btn': 'Enter Ship',
    'account.login.reset': 'Reset password',
    'account.login.error': 'Invalid pirate credentials',
    'account.login.no_account': "Don't have an account? Join the crew",
    'account.register.title': 'Join the Crew',
    'account.register.first': 'First name',
    'account.register.last': 'Last name',
    'account.register.email': 'Email',
    'account.register.phone': 'Phone (WhatsApp)',
    'account.register.pass': 'Password (min. 6 characters)',
    'account.register.btn': 'Create my account',
    'account.register.error': 'Could not create the account',
    'account.register.have_account': 'Already have an account? Sign in',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know for your next mission.',
    'faq.still_doubts': 'Still have questions?',
    'faq.contact': 'Contact us via WhatsApp',
    'faq.q1': 'How long does my order take to arrive?',
    'faq.a1': 'Processing time is 7 to 15 business days, as each piece is made to order to ensure maximum quality. Once shipped, delivery time depends on the carrier (Estafeta or FedEx), usually 2 to 5 days.',
    'faq.q2': 'Do you ship all over Mexico?',
    'faq.a2': 'Yes, we ship to all of Mexico through Envia.com with the best couriers in the country.',
    'faq.q3': 'How can I track my package?',
    'faq.a3': 'You can track it directly in our \'My Account\' section if you are registered, or by entering the tracking number we will send you by email in the corresponding carrier\'s official portal.',
    'faq.q4': 'Do you have a physical store?',
    'faq.a4': 'Currently we operate exclusively online to offer the widest variety of designs to nakamas across Mexico.',
    'faq.q5': 'What care should I take with my embroidered garment?',
    'faq.a5': 'We recommend washing the garment inside out with cold water, do not use a dryer, and never iron directly on the embroidery to preserve thread density and color.',

    // Size Guide
    'sizes.title': 'Size Guide',
    'sizes.subtitle': 'Make sure your gear fits perfectly before sailing.',
    'sizes.badge': 'Guide',
    'sizes.pro_tip': '💡 Nakama Pro-Tip',
    'sizes.pro_tip_text': 'Our sizes are standard Mexican sizes. If you are looking for a more relaxed or \'baggy\' style, we recommend ordering one size up from your usual, especially for our embroidered pieces.',
    'sizes.cat.tshirts': 'T-Shirts',
    'sizes.cat.oversize': 'Oversize',
    'sizes.cat.sweatshirts': 'Sweatshirts',
    'sizes.cat.hoodies': 'Hoodies',
    'sizes.cat.acid': 'Acid Wash',
    'sizes.cat.shorts': 'Shorts',
    'sizes.cat.chroma': 'Chroma',

    // Legal
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'Protecting your data like the One Piece.',
    'terms.title': 'Terms & Conditions',
    'terms.subtitle': 'The rules of this ship for a safe navigation.',

    // Cookies
    'cookies.title': 'Cookie notice',
    'cookies.text': 'We use our own and third-party cookies (Google Analytics and Meta) to analyze browsing and improve your experience. The store\'s essential features do not depend on them.',
    'cookies.link': 'See our Privacy Notice',
    'cookies.accept': 'Accept',
    'cookies.reject': 'Reject',

    // Bot
    'bot.welcome': 'Oi, Nakama! 🍖 I\'m Luffy, the guardian of this ship. Don\'t waste time typing, just tap the buttons to find your treasure! 🏴‍☠️',
    'bot.status': '● NAVIGATING THE MENU',
    'bot.hint': 'Where are we sailing, Nakama?',
    'bot.btn.all': '🔥 View Full Catalog',
    'bot.btn.embroidery': '🪡 View Embroidery',
    'bot.btn.prints': '👕 View Prints',
    'bot.btn.special': '✨ Special Edition',
    'bot.btn.sizes': '📐 Size Guide',
    'bot.btn.tracking': '🔍 Order Tracking',
    'bot.btn.faq': '❓ FAQ',
    'bot.btn.privacy': '📄 Privacy Policy',
    'bot.btn.crew': '🏴‍☠️ Talk to Crew',
    
    // Global & UI
    'cart.title': 'Your Loot',
    'cart.empty': 'Your cart is empty',
    'checkout.button': 'Go to Checkout',
    'theme.dark': 'Dark Mode',
    'theme.light': 'Light Mode',
    
    // Footer
    'footer.description': 'Forging the gear for the next Pirate Kings. High density anime streetwear.',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.secure_payment': 'Secure Payment',
    'footer.rights': 'All rights reserved.',
    'footer.faq': 'FAQ',
    'footer.size_guide': 'Size Guide',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.dev': 'Design & Development',
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = 'user-language';
const LANGUAGE_CHANGE_EVENT = 'nakama-language-change';

const getServerLanguage = (): Language => 'es';

const getStoredLanguage = (): Language => {
  const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return saved === 'en' ? 'en' : 'es';
};

const subscribeToLanguage = (onStoreChange: () => void) => {
  window.addEventListener('storage', onStoreChange);
  window.addEventListener(LANGUAGE_CHANGE_EVENT, onStoreChange);

  return () => {
    window.removeEventListener('storage', onStoreChange);
    window.removeEventListener(LANGUAGE_CHANGE_EVENT, onStoreChange);
  };
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const language = useSyncExternalStore(
    subscribeToLanguage,
    getStoredLanguage,
    getServerLanguage,
  );

  const setLanguage = (lang: Language) => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
    window.dispatchEvent(new Event(LANGUAGE_CHANGE_EVENT));
  };

  const t = (key: string) => {
    return translations[language][key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
