name: Deploy to Staging via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build Project
        run: npm run build
        env:
          NEXT_PUBLIC_WP_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_WP_GRAPHQL_URL || 'https://nakamabordados.com/graphql' }}

      - name: 📁 Prepare Deployment Folder
        run: |
          mkdir deploy
          cp -r .next/standalone/* deploy/
          cp -r public deploy/
          mkdir -p deploy/.next/static
          cp -r .next/static/* deploy/.next/static/

      - name: 🚀 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/
          server-dir: /public_html/test/ # REEMPLAZAR con la carpeta real de tu subdominio
          dangerous-clean-slate: false
